# Generated by Django 6.0.5 on 2026-05-14 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bidfinalization',
            name='account_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='bidfinalization',
            name='bank_account',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='bidfinalization',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bidfinalization',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bidfinalization',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bidfinalization',
            name='credit_card_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='bidfinalization',
            name='cvc',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bidfinalization',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bidfinalization',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidfinalization',
            name='national_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='bidfinalization',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit card'), ('bank_transfer', 'Bank transfer'), ('wire_transfer', 'Wire transfer')], max_length=30),
        ),
        migrations.AddField(
            model_name='bidfinalization',
            name='postal_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='bidfinalization',
            name='routing_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='bidfinalization',
            name='sending_bank',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bidfinalization',
            name='street_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='seller',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seller',
            name='postal_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='seller',
            name='street_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('artwork', 'bidder'), name='unique_bid_per_artwork_and_bidder'),
        ),
    ]
